

services:
  broker01:
    image: confluentinc/cp-kafka:7.9.2
    container_name: broker01
    hostname: broker01
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 10
      #KAFKA_KRAFT_MODE: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper01:2181,zookeeper02:2181,zookeeper03:2181
      KAFKA_LISTENERS: PLAINTEXT://broker01:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:9092, PLAINTEXT://broker01:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_NUM_PARTITIONS: 3
    # extends:
    #    file: kafka-extend.yml
    #    service: kafka
    volumes:
       - ./data/broker01:/var/lib/kafka/data
  broker02:
    image: confluentinc/cp-kafka:7.9.2
    container_name: broker02
    hostname: broker02
    ports:
      - "9093:9093"
      - "29093:29093"
    environment:
      KAFKA_NODE_ID: 11
      #KAFKA_KRAFT_MODE: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper01:2181,zookeeper02:2181,zookeeper03:2181
      KAFKA_LISTENERS: PLAINTEXT://broker02:29093,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:9093, PLAINTEXT://broker02:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_NUM_PARTITIONS: 3      
    # extends:
    #    file: kafka-extend.yml
    #    service: kafka      
    volumes:
       - ./data/broker02:/var/lib/kafka/data    
  broker03:
    image: confluentinc/cp-kafka:7.9.2
    container_name: broker03
    hostname: broker03
    ports:
      - "9094:9094"
      - "29094:29094"
    environment:
      KAFKA_NODE_ID: 12
      #KAFKA_KRAFT_MODE: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper01:2181,zookeeper02:2181,zookeeper03:2181
      KAFKA_LISTENERS: PLAINTEXT://broker03:29094,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:9094, PLAINTEXT://broker03:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_NUM_PARTITIONS: 3        
    # extends:
    #    file: kafka-extend.yml
    #    service: kafka
    volumes:
       - ./data/broker03:/var/lib/kafka/data